// Generated by .impeccable/brand/scripts/build-brand.mjs. Edit the script, not this file.
import type { SVGProps } from "react";

const FRAME_64: ReadonlyArray<readonly [number, number, number, number]> = [
  [4, 4, 56, 4],
  [4, 8, 4, 52],
  [56, 8, 4, 52],
  [4, 56, 16, 4],
  [36, 56, 24, 4],
  [10, 10, 44, 2],
  [10, 12, 2, 42],
  [52, 12, 2, 42],
  [10, 52, 10, 2],
  [36, 52, 18, 2],
];
const Y_64 = "M17.75 16H26.25L32 32.1L37.75 16H46.25L29.11 64H20.61L27.75 44Z";
const HINT_24: ReadonlyArray<readonly [number, number, number, number]> = [
  [1, 1, 22, 2],
  [1, 3, 2, 20],
  [21, 3, 2, 20],
  [3, 21, 5, 2],
  [15, 21, 6, 2],
  [4, 4, 16, 1],
  [4, 5, 1, 14],
  [19, 5, 1, 14],
  [4, 19, 4, 1],
  [15, 19, 5, 1],
  [7, 7, 3, 3],
  [8, 10, 3, 3],
  [9, 13, 3, 3],
  [14, 7, 3, 3],
  [13, 10, 3, 3],
  [12, 13, 3, 3],
  [11, 16, 3, 3],
  [10, 19, 3, 3],
  [9, 22, 3, 2],
];
const HINT_16: ReadonlyArray<readonly [number, number, number, number]> = [
  [1, 1, 14, 1],
  [1, 2, 1, 13],
  [14, 2, 1, 13],
  [2, 14, 3, 1],
  [11, 14, 3, 1],
  [3, 3, 2, 3],
  [4, 6, 2, 3],
  [5, 9, 2, 2],
  [6, 11, 2, 1],
  [11, 3, 2, 3],
  [10, 6, 2, 3],
  [9, 9, 2, 2],
  [8, 11, 2, 2],
  [7, 13, 2, 3],
];
const WORD =
  "M0.85 20H7.15L11 33.2L14.85 20H21.15L10.07 58H3.76L7.85 44ZM26 20H32V44H26ZM26 29A10 10 0 0 1 46 29V44H40V29A4 4 0 0 0 32 29V44H26ZM40 29A10 10 0 0 1 60 29V44H54V29A4 4 0 0 0 46 29V44H40ZM65 32A13 13 0 1 1 91 32A13 13 0 1 1 65 32ZM71 32A7 7 0 1 0 85 32A7 7 0 1 0 71 32ZM85 8H91V44H85Z";

const rects = (list: ReadonlyArray<readonly [number, number, number, number]>) =>
  list.map(([x, y, width, height]) => (
    <rect key={`${x}-${y}-${width}-${height}`} x={x} y={y} width={width} height={height} />
  ));

type IsotypeProps = Omit<SVGProps<SVGSVGElement>, "viewBox"> & {
  /** Rendered size in CSS px. 16 and 24 use pixel-hinted drawings; larger sizes use the 64 master. */
  size?: number;
  title?: string;
};

/** The ymd stamp mark. Inherits currentColor. */
export function Isotype({ size = 24, title = "ymd", ...rest }: IsotypeProps) {
  const grid = size <= 16 ? 16 : size <= 24 ? 24 : 64;
  const body =
    grid === 16 ? (
      rects(HINT_16)
    ) : grid === 24 ? (
      rects(HINT_24)
    ) : (
      <>
        {rects(FRAME_64)}
        <path d={Y_64} />
      </>
    );
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={`0 0 ${grid} ${grid}`}
      width={size}
      height={size}
      role="img"
      aria-label={title}
      shapeRendering={grid === 64 ? undefined : "crispEdges"}
      fill="currentColor"
      {...rest}
    >
      {body}
    </svg>
  );
}

type LogotypeProps = Omit<SVGProps<SVGSVGElement>, "viewBox"> & {
  /** Rendered height in CSS px; width follows the 176:64 ratio. */
  height?: number;
  title?: string;
};

/** Stamp mark in var(--accent) + "ymd" wordmark in currentColor. */
export function Logotype({ height = 32, title = "ymd", ...rest }: LogotypeProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 176 64"
      height={height}
      width={(height * 176) / 64}
      role="img"
      aria-label={title}
      {...rest}
    >
      <g style={{ fill: "var(--accent, #6B3FA0)" }}>
        {rects(FRAME_64)}
        <path d={Y_64} />
      </g>
      <path transform="translate(84 0)" fill="currentColor" d={WORD} />
    </svg>
  );
}
