// yt-dlp's supported-sites list, generated by scripts/gen-supported-sites.mjs and refreshed
// weekly by .github/workflows/supported-sites.yml. Shipped with the app; no network at runtime.
import data from "./supported-sites.json";

export interface SupportedSite {
  /** yt-dlp extractor name, e.g. "vimeo:album" */
  name: string;
  description: string;
  /** netrc machine: the key ymd stores the account under (only extractors with login) */
  netrc?: string;
  /** marked "Currently broken" by yt-dlp */
  broken?: boolean;
}

export interface SupportedSitesData {
  source: string;
  fetchedAt: string;
  count: number;
  sites: SupportedSite[];
}

export const SUPPORTED_SITES = data as SupportedSitesData;

/** Human page with the same list (the JSON source is the raw file). */
export const SUPPORTED_SITES_PAGE =
  "https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md";
export const YTDLP_ISSUES_URL = "https://github.com/yt-dlp/yt-dlp/issues";

/** Same alphabet as `normalize_key` in src-tauri/src/auth/keychain.rs (and yt-dlp's netrc). */
export const SITE_KEY = /^[a-z0-9.][a-z0-9._-]*$/;

/** Normalise free text the way the keychain will; null when it would be rejected. */
export function normalizeSiteKey(raw: string): string | null {
  const key = raw.trim().toLowerCase();
  return SITE_KEY.test(key) ? key : null;
}

/** netrc machines that do not take a password in yt-dlp (cookies only). */
export const COOKIES_ONLY = new Set(["youtube"]);

export interface AccountSite {
  /** netrc machine stored in the keychain */
  key: string;
  /** readable name: the extractor named like the key, else the shortest one */
  name: string;
  description: string;
  /** every extractor that logs in with this key */
  extractors: string[];
  broken: boolean;
}

/** One entry per netrc machine, for the "Cuentas por sitio" picker. */
export function accountSites(sites: SupportedSite[] = SUPPORTED_SITES.sites): AccountSite[] {
  const groups = new Map<string, SupportedSite[]>();
  for (const s of sites) {
    if (!s.netrc) continue;
    const list = groups.get(s.netrc);
    if (list) list.push(s);
    else groups.set(s.netrc, [s]);
  }
  const out: AccountSite[] = [];
  for (const [key, list] of groups) {
    const ranked = [...list].sort(
      (a, b) =>
        Number(b.name.toLowerCase() === key) - Number(a.name.toLowerCase() === key) ||
        Number(a.name.includes(":")) - Number(b.name.includes(":")) ||
        a.name.length - b.name.length,
    );
    const main = ranked[0];
    out.push({
      key,
      name: main.name,
      // only the main extractor's own words: a sibling's ("Vimeo user likes") would mislead
      description: main.description,
      extractors: list.map((s) => s.name),
      broken: list.every((s) => s.broken),
    });
  }
  return out.sort((a, b) => a.name.localeCompare(b.name, "en", { sensitivity: "base" }));
}

/** Lowercase, accent-free text for matching. */
export function fold(text: string): string {
  return text.normalize("NFD").replace(/\p{M}/gu, "").toLowerCase();
}

export type SiteFilter = "all" | "account" | "broken";

export function filterSites(
  sites: SupportedSite[],
  query: string,
  filter: SiteFilter,
): SupportedSite[] {
  const q = fold(query.trim());
  const kept = sites.filter(
    (s) => filter === "all" || (filter === "account" ? !!s.netrc : !!s.broken),
  );
  if (!q) return kept;
  // name prefix, then name, then description or netrc key; alphabetical within each rank
  const ranks: SupportedSite[][] = [[], [], []];
  for (const s of kept) {
    const name = fold(s.name);
    if (name.startsWith(q)) ranks[0].push(s);
    else if (name.includes(q)) ranks[1].push(s);
    else if (fold(s.description).includes(q) || s.netrc?.includes(q)) ranks[2].push(s);
  }
  return ranks.flat();
}
